#!/bin/bash
i=0;
for field in `sed "s/ \+/\t/g" < $1 | cut -f 3-4 | sed "s/\t/_/g"`;
do
	echo -n "$( cut -f 1 -d _ <<< "$field" ) * cos( 2 * pi * ${i} * x ) + "
	echo -n "$( cut -f 2 -d _ <<< "$field" ) * sin( 2 * pi * ${i} * x ) + "
	i=$(($i+1));
done
echo
